name: ci

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven Project
      run: mvn -B package --file pom.xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
